global:
  scrape_interval: 10s #  data refresh rate
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'product_service'
    metrics_path: '/actuator/prometheus' #where come from data
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:49580']
  - job_name: 'order_service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:8081' ]
  - job_name: 'inventory_service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:49593' ]